# Generated by Django 4.0.3 on 2022-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarModel', models.CharField(max_length=60)),
                ('CarDescription', models.TextField(blank=True, null=True)),
                ('CarColor', models.TextField(blank=True, max_length=30, null=True)),
                ('CarYear', models.IntegerField(blank=True, max_length=30, null=True)),
                ('RentPrice', models.IntegerField()),
                ('CarUsing', models.BooleanField()),
            ],
        ),
    ]
