# Generated by Django 4.0.3 on 2022-06-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='CarYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
