# Generated by Django 4.0.3 on 2022-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_alter_car_caryear'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='CarImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
