# Generated by Django 4.0.3 on 2022-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_car_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='UserRentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
